server:
  port: 8090

spring:
  application:
    name: storeService
  datasource:
    username: 'testUser'
    url: jdbc:postgresql://postgres-clusterip-srv:5432/testDB
    password: 'testPassword'
spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: 'true'
  hibernate:
    ddl-auto: update
  show-sql: 'true'