server:
  port: 8090

spring:
  application:
    name: storeService
  datasource:
    username: 'ggichev'
    url: jdbc:postgresql://localhost:5432/store
    password: 'pa55w0rd!'
spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: 'true'
  hibernate:
    ddl-auto: update
  show-sql: 'true'