version: 'v1'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ggichev
      POSTGRES_PASSWORD: pa55w0rd!
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: georgi.gichev87@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pa55w0rd!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    
    
networks:
  postgres:
    driver: bridge
    
    
volumes:
  postgres:
  pgadmin:
    